### ISSUE TITLE
weight and weightlessness, "apparent" or otherwise

### ISSUE THREAD

**Issue by JohnDenker** [ericmazur/PnPbook#111]
See item #107 for a catalog of related issues.

The concept of "apparent" weight and ""apparent" weightlessness is introduced in section 13.3 on page 320.

This is  Bad Idea.  Weight is weight.  The notion of "apparent" weight is not useful.  Also spring scales do not make weight any more "apparent" or any less real.  The weight or lack thereof does not depend on whether you measure it with a spring scale or otherwise, e.g. by dropping it and seeing what happens.

The passage in the right-hand column says the astronauts are only "apparently" weightless, flatly contradicting the left-hand column that says they are weightless.

If you have a non-ideal scale, corrections must be applied, but other than that, trying to make a three-way distinction between weight, the force of gravity, and scale readings introduces multiple layers of needless complexity and obscures the physics.  It complicates the simple part of the story without simplifying the one slightly-complicated part of the story.

**Comment by ericmazur** [comment]
The real problem is equating "weight" with "force of gravity". I'm essentially skirting the whole issue by not talking about weight in the book, except for that section. I think it's fine.
