### ISSUE TITLE
conservation / continuity conformance

### ISSUE THREAD

**Issue by JohnDenker** [ericmazur/PnPbook#42]
This is a _blocking_ issue for bug #41 and arguably also bug #1.

According to the index, the concept of **conservation of charge** is presented only once, namely in section 22.3 on page 602.  It is expressed in words, not as an equation.

According to the index, the **continuity equation** appears only once in the book, namely equation 18.23 on page 491.  Alas, that is only a watered-down corollary, applicable to _steady_ flow of a fluid in _one dimension_.

It would be nice to see a formal equation that expresses conservation of charge and continuity of current.  Presumably this would have to be the integral form:
  https://en.wikipedia.org/wiki/Continuity_equation#Integral_form
in order to be consistent with the avoidance of partial derivatives elsewhere in the book.

Specific suggestions:  If I were doing it

1) Fairly early on, I would introduce the continuity / conservation equation and explain how to interpret it.  I would link to the places where it is applied, including fluids, charge, energy, momentum, et cetera.

2) I would mark equation 18.23 as not "THE" continuity equation but only a watered-down special case thereof ... and I would link to the more general expression.

3) I would emphasize that current is not conserved.  There is no such thing as "conservation" of current.  There is only **conservation of charge** and **continuity of current**.

4) After the conservation / continuity equation is well established, I would point out that it can be derived as a corollary of the Maxwell equations, as mentioned in issue #41.

5) I would index all of this multiple ways, so that it can be found under "continuity" and also under "conservation" et cetera.  See #181 for a catalog of index-related issues.

**Comment by ericmazur** [comment]
Regarding your step 1 -- I could do that in Ch18. Or -- but I'm a bit hesitant to do that -- I could introduce it when I talk for the first time about systems and extensive quantities. Actually, I sort of do it, but only in a conceptual way. 

By the way, that wikipedia article is kind of screwed up. At the top: "A continuity equation in physics is an equation that describes the transport of a conserved quantity"  Baloney! It holds for any extensive quantity. In fact, farther down, in the second boxed equation they include a source term (Sigma = "net rate that q is being generated inside the volume V"), which is zero for any conserved quantity.

**Comment by JohnDenker** [comment]
I wouldn't be too harsh on the wikipedia article, because the PnP book is screwed up in all the same ways, and more besides.  The thing the book emphatically calls "the" continuity equation (18.23) is restricted to conserved quantities, further restricted to steady flow, and yet further restricted to one dimension.

The wikipedia article is fixable.
